# config/config.yaml
# 网关基础配置
gateway:
  gatewayId: 3-3-JC-1F-中控室
  ipAddress: 172.18.79.100
  alias: 3-3-JC-1F-中控室

  # 采集轮询策略
  polling:
    period: 1
    heartbeatIntervalMs: 3000
    collectIntervalMs: 600000
    changeThreshold: 0.01

# PLC连接配置
plc:
  ip: 172.18.79.6
  port: 102
  timeout: 10000
  rack: 0
  slot: 1
  plcID: 3-3-6

  # 寄存器映射电表的配置，每个寄存器对应一个电表，设备ID为电表ID
  registers:
    - deviceNumber: 1
      deviceId: AHU41
      alias: three_phase_electric_meter
      dbNumber: 10
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 2
      deviceId: AHU42
      alias: three_phase_electric_meter
      dbNumber: 11
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 3
      deviceId: AHU43
      alias: three_phase_electric_meter
      dbNumber: 12
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 4
      deviceId: AHU44
      alias: three_phase_electric_meter
      dbNumber: 13
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 5
      deviceId: AHU107
      alias: three_phase_electric_meter
      dbNumber: 14
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 6
      deviceId: AHU108
      alias: three_phase_electric_meter
      dbNumber: 15
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 7
      deviceId: AHU45
      alias: three_phase_electric_meter
      dbNumber: 16
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 8
      deviceId: 2APZ1
      alias: three_phase_electric_meter
      dbNumber: 17
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 9
      deviceId: 2APZ2
      alias: three_phase_electric_meter
      dbNumber: 18
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 10
      deviceId: AHU46
      alias: three_phase_electric_meter
      dbNumber: 19
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 11
      deviceId: 2#CSJ-02
      alias: three_phase_electric_meter
      dbNumber: 20
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 12
      deviceId: AHU47
      alias: three_phase_electric_meter
      dbNumber: 21
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 13
      deviceId: AHU48
      alias: three_phase_electric_meter
      dbNumber: 22
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 14
      deviceId: 3-3-6捷瑞除湿机
      alias: three_phase_electric_meter
      dbNumber: 23
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 15
      deviceId: AHU49
      alias: three_phase_electric_meter
      dbNumber: 24
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

    - deviceNumber: 16
      deviceId: AHU50
      alias: three_phase_electric_meter
      dbNumber: 25
      startOffset: 92
      endOffset: 96
      length: 4
      dataType: float

# MQTT配置
mqtt:
  broker: tcp://10.79.27.187:1886
  clientId: 3-3-JC-2F-6#PLC
  qos: 1

  username: mqtt6
  password: 123123
  cleanStart: true
  keepAlive: 10
  timeout: 300
  autoReconnect: true
  msgExample: KFC-CRAZY-THURSDAY-VWO50

  subTopic: device/byd_power/down/
  subQos: 1

  pubTopic: energy/electric/
  pubQos: 1

